### ISSUE TITLE
how to fix ???

### ISSUE THREAD

**Issue by dnmnhat** [andrejrcarvalho/OrangePi_SSD1306#1]
root@orangepilite:~/OrangePi_SSD1306# sudo make clean all
rm -f *.o core.* *~ display.out *.bak .h .c
g++ -Wall -Wextra -ggdb -pedantic -D_POSIX_C_SOURCE=200809L -O  -c main.cpp
g++ -Wall -Wextra -ggdb -pedantic -D_POSIX_C_SOURCE=200809L -O  -c SSD1306.cpp
g++ -Wall -Wextra -ggdb -pedantic -D_POSIX_C_SOURCE=200809L -O  -c ubuntuMono8pt.cpp
g++ -Wall -Wextra -ggdb -pedantic -D_POSIX_C_SOURCE=200809L -O  -c system_info.cpp
g++ -o display.out main.o SSD1306.o ubuntuMono8pt.o system_info.o -lpthread -lwiringPi
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../../lib/libwiringPi.so: undefined reference to `shm_open'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../../lib/libwiringPi.so: undefined reference to `crypt'
collect2: error: ld returned 1 exit status
make: *** [makefile:39: display.out] Error 1

**Comment by andrejrcarvalho** [comment]
Hi
Try to add '-lrt' to the LDFLAGS on the makefile (line10): `LDFLAGS=-lrt`
And make sure that you have the wiringPi library installed

**Comment by dnmnhat** [comment]
I added 
`LDFLAGS=-lrt -lcrypt`
and it worked for me
